version: '3'

services:
  mybackend:
    container_name: mybackend
    build:
      dockerfile: Dockerfile
      context: ./mybackend
    networks:
      - frontend_network
      - backend_network

  myfrontend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./myfrontend
    networks:
      - frontend_network
    ports:
      - 3000:3000

  mydb:
    container_name: mydb
    image: mongo
    networks:
      - backend_network
  
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
