apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deplo
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
        env:
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: USER
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: PASSWORD
        ports:
          - containerPort: 27017
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mydb-pvc