apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-deplo
spec:
  selector:
    matchLabels:
      app: mikro-a
  template:
    metadata:
      labels:
        app: mikro-a
    spec:
      containers:
      - name: mikro-a
        image: xkuklix/lab11:zad1.a.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
