version: '3'

services:
  db:
    container_name: db
    image: mongo:4.1.13
    networks:
      - net_A
    volumes:
      - mydb:/data/db
    ports:
      - 27019:27017
  server:
    container_name: server
    image: xkuklix/test:test
    depends_on:
      - db
    networks:
      - net_A
    ports:
      - 3003:3003

volumes:
  mydb: {}

networks:
  net_A:
    driver: bridge